// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type SubscribeMessageReq struct {
	Group string `json:"group"` // 订阅组
}

type SubscribeMessageResp struct {
	Success bool `json:"success"`
}
