// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSubscribe = "subscribe"

// Subscribe mapped from table <subscribe>
type Subscribe struct {
	ID         int64      `gorm:"column:id;primaryKey" json:"id"`
}

// TableName Subscribe's table name
func (*Subscribe) TableName() string {
	return TableNameSubscribe
}
