// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	subscribe "zero-fusion/app/demo/api/internal/handler/subscribe"
	"zero-fusion/app/demo/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterMajorHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 订阅消息
				Method:  http.MethodPost,
				Path:    "/subscribe",
				Handler: subscribe.SubscribeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
